language: python
dist: xenial
sudo: true
matrix:
  include:
    - python: 2.7
    - python: 3.5
      env: PYTHONFAULTHANDLER=1
    - python: 3.6
      env: PYTHONFAULTHANDLER=1
    - python: 3.7
      env: PYTHONFAULTHANDLER=1 PYTEST_ADDOPTS="--doctest-modules"
before_install:
  - sudo apt-get update -q
  - sudo apt-get install --no-install-recommends -y gdb xvfb python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
install:
  - pip install -r requirements.txt
  - pip install -r requirements2.txt
before_script:
  - ulimit -c unlimited -S  # Enable core dumps
script:
  - xvfb-run pytest
after_success:
  - coveralls
after_failure:
  - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)  # Find core dump file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" python -ex "thread apply all bt" -ex "set pagination 0" -batch; fi