language: python
dist: xenial
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-dev python3-gi python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
install:
  - pip install -r requirements.txt
script:
  - pytest